import { test, expect } from '@playwright/test';
export const E2E_PORT = process.env.E2E_PORT || 3000;

// Run tests in this file with portrait-like viewport.
test.use({ viewport: { width: 1600, height: 1200 } });

test.beforeEach(async ({page}) => {
    const url = `http://localhost:3000/`
    await page.goto(url, {waitUntil: 'load'})
    await expect(page).toHaveTitle('TabManager Playground')
})

test('init test', async ({ page }) => {
    const window = await page.locator('.PlaygroundTabManagerTheme__window')
    await expect(await window.innerHTML()).toBe('<div class="PlaygroundTabManagerTheme__tab-group PlaygroundTabManagerTheme__active" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div>')
});


test('click test', async ({ page }) => {

    const window = await page.locator('.PlaygroundTabManagerTheme__window')

    await page.locator('text=Jenny').click();
    await expect(await window.innerHTML()).toBe('<div class="PlaygroundTabManagerTheme__tab-group PlaygroundTabManagerTheme__active" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"><div class="PlaygroundTabManagerTheme__tab-group-bar-item PlaygroundTabManagerTheme__active"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">Jenny</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: block;"><div name="Jenny" active="true" type="tab" version="1"><h1 class="user">name：Jenny</h1><div>gender: female</div><div><select><option>0</option><option>1</option></select></div></div></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div>')

    await page.locator('.PlaygroundTabManagerTheme__window > div:nth-child(2)').click();
    await expect(await window.innerHTML()).toBe('<div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"><div class="PlaygroundTabManagerTheme__tab-group-bar-item PlaygroundTabManagerTheme__active"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">Jenny</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: block;"><div name="Jenny" active="true" type="tab" version="1"><h1 class="user">name：Jenny</h1><div>gender: female</div><div><select><option>0</option><option>1</option></select></div></div></div></div><div class="PlaygroundTabManagerTheme__tab-group PlaygroundTabManagerTheme__active" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div>')

    await page.locator('text=Tom').click();
    await expect(await window.innerHTML()).toBe('<div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"><div class="PlaygroundTabManagerTheme__tab-group-bar-item PlaygroundTabManagerTheme__active"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">Jenny</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: block;"><div name="Jenny" active="true" type="tab" version="1"><h1 class="user">name：Jenny</h1><div>gender: female</div><div><select><option>0</option><option>1</option></select></div></div></div></div><div class="PlaygroundTabManagerTheme__tab-group PlaygroundTabManagerTheme__active" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"><div class="PlaygroundTabManagerTheme__tab-group-bar-item PlaygroundTabManagerTheme__active"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">Tom</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: block;"><div name="Tom" active="true" type="tab" version="1"><h1 class="user">name：Tom</h1><div>gender: male</div><div><select><option>0</option><option>1</option></select></div></div></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div>')

    await page.locator('text=John').click();
    await expect(await window.innerHTML()).toBe('<div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"><div class="PlaygroundTabManagerTheme__tab-group-bar-item PlaygroundTabManagerTheme__active"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">Jenny</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: block;"><div name="Jenny" active="true" type="tab" version="1"><h1 class="user">name：Jenny</h1><div>gender: female</div><div><select><option>0</option><option>1</option></select></div></div></div></div><div class="PlaygroundTabManagerTheme__tab-group PlaygroundTabManagerTheme__active" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"><div class="PlaygroundTabManagerTheme__tab-group-bar-item"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">Tom</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div><div class="PlaygroundTabManagerTheme__tab-group-bar-item PlaygroundTabManagerTheme__active"><div class="PlaygroundTabManagerTheme__tab-group-bar-item-text">John</div><button class="PlaygroundTabManagerTheme__tab-group-bar-item-button"><img src="/@fs/Users/wing/Develop/meogic-tab-manager/packages/tab-manager-tab-group-bar/src/assets/close.svg" alt="close"></button></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: none;"><div name="Tom" active="false" type="tab" version="1"><h1 class="user">name：Tom</h1><div>gender: male</div><div><select><option>0</option><option>1</option></select></div></div></div><div class="PlaygroundTabManagerTheme__tab" data-tab-manager-tab="true" style="display: block;"><div name="John" active="true" type="tab" version="1"><h1 class="user">name：John</h1><div>gender: male</div><div><select><option>0</option><option>1</option></select></div></div></div></div><div class="PlaygroundTabManagerTheme__tab-group" style="flex-grow: 33.33;"><div class="PlaygroundTabManagerTheme__tab-group-resize-handle" data-tab-manager-resize-handle="true"></div><div class="PlaygroundTabManagerTheme__tab-group-bar"></div></div>')

});
